version: '3'

services:

  stock-service:
    image: otodosov/user-management:latest
    container_name: user-management
    ports:
      - 8080:8080
    environment:
      - UM_DB_CONNECTION_URL=jdbc:postgresql://db:5432/postgres?currentSchema\=public
      - UM_DB_USERNAME=postgres
      - UM_DB_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123